### ISSUE TITLE
Getting errors in munin-cron

### ISSUE THREAD

**Issue by lthown** [silverchris/Android-Munin-Node#2]
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Android' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Fork' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Firewall' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Inode' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Network' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Munin' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Cell' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Android' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Fork' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Firewall' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Inode' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Network' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Munin' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:14 [WARNING] munin_set_var_loc: Setting unknown option 'Cell' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:22 [WARNING] munin_set_var_loc: Setting unknown option 'Android' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:22 [WARNING] munin_set_var_loc: Setting unknown option 'Fork' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:22 [WARNING] munin_set_var_loc: Setting unknown option 'Firewall' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:22 [WARNING] munin_set_var_loc: Setting unknown option 'Inode' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:22 [WARNING] munin_set_var_loc: Setting unknown option 'Network' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:22 [WARNING] munin_set_var_loc: Setting unknown option 'Munin' at DroidX;DroidX;android_eXXXXX:
2011/06/23 19:22:22 [WARNING] munin_set_var_loc: Setting unknown option 'Cell' at DroidX;DroidX;android_eXXXXX:

**Comment by lthown** [comment]
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label ifb0trans
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label sit0trans
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label lotrans
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label tiwlan0rcvd
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label usb0rcvd
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label lorcvd
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label ifb1rcvd
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label ppp0rcvd
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label tiwlan0trans
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label ip6tnl0rcvd
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label ip6tnl0trans
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label ppp0trans
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label sit0rcvd
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label ifb0rcvd
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label ifb1trans
2011/06/23 19:27:21 [WARNING] Service Network_Errors on DroidX/127.0.0.1:4949 returned no data for label usb0trans
2011/06/23 19:27:21 [WARNING] Service Firewall_Packets on DroidX/127.0.0.1:4949 returned no data for label forwarded
2011/06/23 19:27:21 [WARNING] Service Firewall_Packets on DroidX/127.0.0.1:4949 returned no data for label received

**Comment by silverchris** [comment]
Hey, could I get the version of munin you are using, and your plugins-conf.d with the android entries in it, and the data file in the data folder?
Thanks

**Comment by lthown** [comment]
Munin version 1.4.4

/etc/munin/plugin-conf.d/munin-node:
[android_eXXXXX]
host_name DroidX-Bair.Android

Data File:

…
Android UptimeÃgraph_title Android Uptime
graph_args --base 1000 -l 0
graph_scale no
graph_vlabel time in days
graph_category Android Phone
booted.label booted
booted.draw AREA
awake.label awake
awake.draw AREA-booted.value 0.85842067
awake.value 0.7210849
­
Battery¯graph_title Battery Charge
graph_args --upper-limit 100 -l 0
graph_scale no
graph_vlabel %
graph_category Android Phone
graph_info This graph shows battery charge in %
battery.label Battery Charge
charge.label Charging
multigraph Battery_Temp
graph_title Battery Temp
graph_vlabel Temp
graph_category Android Phone
graph_info This graph shows battery Temp
temp.label Battery Temperature
multigraph Battery_Volt
graph_title Battery Voltage
graph_vlabel Voltage
graph_category Android Phone
graph_info This graph shows battery Voltage
volt.label Battery Voltagepbattery.value 90.0
charge.value 0
multigraph Battery_Temp
temp.value 40.0
multigraph Battery_Volt
volt.value 3.0


CPUÜgraph_title CPU usage
graph_order system user nice idle iowait irq softirq
graph_args --base 1000 -r --lower-limit 0 --upper-limit 100
graph_vlabel %
graph_scale no
graph_info This graph shows how CPU time is spent.
graph_category system
graph_period second
system.label system
system.draw AREA
system.min 0
system.info CPU time spent by the kernel in system activities
user.label user
user.draw STACK
user.min 0
user.info CPU time spent by normal programs and daemons
nice.label nice
nice.draw STACK
nice.min 0
nice.info CPU time spent by nice(1)d programs
idle.label idle
idle.draw STACK
idle.min 0
idle.info Idle CPU time
iowait.label iowait
iowait.draw STACK
iowait.min 0
iowait.info CPU time spent waiting for I/O operations to finish when there is nothing else to do.
irq.label irq
irq.draw STACK
irq.min 0
irq.info CPU time spent handling interrupts
softirq.label softirq
softirq.draw STACK
softirq.min 0
softirq.info CPU time spent handling batched interrupts
steal.label steal
steal.draw STACK
steal.min 0
steal.info The time that a virtual CPU had runnable tasks, but the virtual CPU itself was not running¨user.value 14.752929
nice.value 0.8745118
system.value 9.760571
idle.value 74.61199

iowait.value 1.360163
irq.value 0.23093905
softirq.value 0.11546952
steal.value 0.0


**Comment by lthown** [comment]
Looks like the odd non-ascii characters didn't come through - Going to try base64 of the gzip:

H4sIAAAAAAAAAKVXvW8ktxU/nS+XgEFygIoUWxEGDEvAaTIzu7Mfpe7g4hCfLUSSUx64M1wNs/Nl
kqPFdm5cp0nhwk26NIEBN2nSBCnzL6TKX5JHPnKWu7c6BTAEaPl+JN97fN9Dvn1Kfn3ZFLIVBb3t
tKj56b9O7iTrynda6IrT/U2CW0zeKXpxsWSK0ySOY3pR0djtqZzBtaZ15H3Flryi5jIVDS3YVrmd
nGl+18rtIOKqbBtOlm2reRHhNSQ8Vki2oZe//+ySsA1bc3fGrh0ynBhduDv3rOo5jaN5Np+k8XTm
Dnp4libxfLIgf/sZ+fkrpjWX29MfnoUGcCh9XcKrDwzQdx2XF5WohTZ2eNwMn3z47bgpmlVLb0qh
qKWpKtuNokunR271MLb8hDjMGeJAUzzo9iwmmjtS95UWyNedf3fD644ce3Kw4fQPkJ/wBMtFw78D
xQ3OJdO95Mf0/Kqt9FE9zQYbfONU3Qd/grae0T38HijstkaddwSG1SKOYm9+F2gP2t2aAQ9NzLWH
3m2l47kxHPsTIR+9vro9/c8vQoMAQnu1e3UrCy6p2iqQAhuwbkQOsVPAWdFuGIStkF9T1a40/D6Y
3BLIqt0MoR6/H/rHw/wgCY7bGf5ZxbFEKKo63ujo0G/4CIeCaNEWVPG8bQqCW8417pzDdhXDATXk
TewJq88g2sqlyy3VJadrLhvgBqed9Viuxb3QgitiDOmkmSXSVtL1zeXr3yGNguzyATFNK2tW0U62
8KhaUdYUUB553TaKGDc5EWaJdCDC0ijCLh8SAXtnyXkxCCHG9Y6xWSIdMLY0MrZLy/hN4WLLtgAM
HM/EEh4LGSHiWCFxTEuzAXWJrlpJ3/z2S9raCiDACFS3dCUaoUq6KXlj3CJtgDStLs0VXkGEwqGi
jQiEr9cIAtlQoS5AOkVgdUyLEoxfGZ6igZSTfacVcVnh48rliEcD9h5yseWoD4qBepGXvNgTpzmr
vDCzdkgoyAJOjF27jOIoRJdMU0bvhdQ9RJYRXrKCyr5p2BJcqJlaq5d02Wsb4+E5oRWvVuANa157
BfQc/fXERjDWnWQSzbJ0kS4w5obOOptkSTL3SeVKYDSbxtkswShCbDaJpkmyWBAfD45tNJ7GyXRs
neOZpuN4MV7E2WBOv5Ek2WS6yFJnAA/H5Dl5cvpk9OTR3x+fkmeft6w4/e5pWDoNRNk9BN9hkz86
5bhCV8Gt47XusHCZk9F7lwb/VYF42q6sf2qWQ5xzWnCVS7HkWCpr1mxNPudcKYCYtLOAOQ9Ou/i6
52CPM2Wiq68gwiA/AKeirnkhQKdqex6hMlZ2RiGcer2vwOiFPeDdMxmTf78gz99CaYLp6PtfHbNO
OrHWOWgMWRyDsyAS9q32aqu52uvkyHuvdx2v/MdbyMYEfmiy3pimRqZQWaK9fsi6TtEOJL3TJi2g
42xYB/LAZlSBhtQuC8iT1YpLRVeSc3uGmJt+6oQl0sFUakir4fAew8b+ygvVMei9cKYSOVa4iDgR
ftpFakCD1PeQ5f6qavM1hMW9aeZnPLqLIM9lUQi1PkflI3pZqdbUTQiPjwtI9O3HdGmuYcQo3UpQ
rW+0qOhGChg0moiYN/oKZJ5r6bD+GNpqcA0rig8yb4wImsxdtoSHgvsOsRyumFyDBisB3i+YZvTM
LqGhgyraP4MY2/te2xhRiARMLW1Z/oFBoBTO7ZH3gS2K2DXQH6bTQA5hDzEFs6rg6SDDPx1+MBoQ
DQ1g6GMODkaGs5r9ESQYl6OtLStFK7E2mdoW/CW4rtFy+5JynZ+j2VFgYHyvwW7vwBEOtdpc0k7w
3BaOOnj1mnOIdC0ZRAtsmZBXuFNCptMlh6664tiJVrKtrWDbHoyxtlzjkbotxEoYLwdJ41QNkL3d
QNkQfs92UJ5qI5PrjRHlW5KZhbpyqyBTKv8kVhTS1ryI3MPgBMH8zsYeKhJC+/tWlc/ffPFZuo9b
XT796q2FPqVn6L9zL84yytu6NskxRLang52A/w4cCjurW8iywDNWHNP4dj+XRfRLKL3uup1DlJsP
sV3XbAuxU5jCwT2jirM12ALM1w36IeGxQDOHYLRUcBCAs3NQwgZFROx46+MPCY8FXBwSelFC3DW6
QntF9AszPPC8YjCPmPoCTocsWKq26k3voQ03fYtBfhLR7An15A4PBA9YKNoEad5LGcgno788tUnq
J5bJZJot0jBh/AdZGJbu9DhOF+PZdD9M3DwznU4X8Ic1HrF0Pkun8XSWYg1yH2fjWZqOp/OhYjt4
ksDRiS+BXr15tphM53OsrF6zXRQ5Oek4G8fJHM45N7rvxUkSL+bpxLvFMc3mMI4l8WRnNMcG5M9n
GYxOfhT6+wl5DrMnuOr0zydhO7614P8xBh0MPa6/I08zlhRsqx7o53goCm94bOioo984ZJg1s/l4
nMyGF3zzjJC3PYyq9Ma84h8f7Q0VduMKRyWTVDe7RzlNa/Xop2nd5+X+t6mfjnHisEKg2Jtm/NLM
0djO4HDBK7bF/tA2djx776vW3j60ZWCXa+RLdmYx+YAkqmwUu/6wVqSr+jvROJZXlvDYjqcDHueK
BxU4K5hpby3hsR1XBxxyRdjwRZ7GZGQ0DnydZIvM6+RTKPXs3JE0Swj57wn55WsOJe1a3DWsOv3n
XiQjSK+15He6pPshHY6q4+TxuL68vj104GVTyFYU9KoEF38wloyOfcWkVwlebfgpS3l3W4KMXjgU
35lN/weDENcfpxUAAA==

**Comment by silverchris** [comment]
Hmmm, What version of android is this, and which phone? The Data file looks like its missing some pieces. Could you run the munin plugin and paste the android_eXXXXX and android_eXXXXX config?

**Comment by silverchris** [comment]
Hey, did you solve the problem on your end? or is it still occurring?

**Comment by lthown** [comment]
Sorry, went on vacation.

This is a DroidX (1) running CyanogenMod 7 (Android System 2.3.4).

I think this is what you are asking for: "munin-run android_eXxXXxxX config"
Android Uptime
Battery
CPU

Load
Memory

uptime

Munin Time
Cell Signal
multigraph Android_Uptime
graph_title Android Uptime
graph_args --base 1000 -l 0
graph_scale no
graph_vlabel time in days
graph_category Android Phone
booted.label booted
booted.draw AREA
awake.label awake
awake.draw AREA
multigraph Battery
graph_title Battery Charge
graph_args --upper-limit 100 -l 0
graph_scale no
graph_vlabel %
graph_category Android Phone
graph_info This graph shows battery charge in %
battery.label Battery Charge
charge.label Charging
multigraph Battery_Temp
graph_title Battery Temp
graph_vlabel Temp
graph_category Android Phone
graph_info This graph shows battery Temp
temp.label Battery Temperature
multigraph Battery_Volt
graph_title Battery Voltage
graph_vlabel Voltage
graph_category Android Phone
graph_info This graph shows battery Voltage
volt.label Battery Voltage
multigraph CPU
graph_title CPU usage
graph_order system user nice idle iowait irq softirq
graph_args --base 1000 -r --lower-limit 0 --upper-limit 100
graph_vlabel %
graph_scale no
graph_info This graph shows how CPU time is spent.
graph_category system
graph_period second
system.label system
system.draw AREA
system.min 0
system.info CPU time spent by the kernel in system activities
user.label user
user.draw STACK
user.min 0
user.info CPU time spent by normal programs and daemons
nice.label nice
nice.draw STACK
nice.min 0
nice.info CPU time spent by nice(1)d programs
idle.label idle
idle.draw STACK
idle.min 0
idle.info Idle CPU time
iowait.label iowait
iowait.draw STACK
iowait.min 0
iowait.info CPU time spent waiting for I/O operations to finish when there is nothing else to do.
irq.label irq
irq.draw STACK
irq.min 0
irq.info CPU time spent handling interrupts
softirq.label softirq
softirq.draw STACK
softirq.min 0
softirq.info CPU time spent handling batched interrupts
steal.label steal
steal.draw STACK
steal.min 0
steal.info The time that a virtual CPU had runnable tasks, but the virtual CPU itself was not running
multigraph

multigraph

multigraph

multigraph

multigraph

multigraph Load
graph_title Load average
graph_args --base 1000 -l 0
graph_vlabel load
graph_scale no
graph_category system
load.label load
graph_info The load average of the machine describes how many processes are in the run-queue (scheduled to run immediately).
load.info 5 minute load average
multigraph Memory
graph_args --base 1024 -l 0 --upper-limit 500469760
graph_vlabel Bytes
graph_title Memory usage
graph_category system
graph_info This graph shows what the machine uses memory for.
graph_order apps page_tables swap_cache slab cached buffers free swap
apps.label apps
apps.draw AREA
apps.info Memory used by user-space applications.
buffers.label buffers
buffers.draw STACK
buffers.info Block device (e.g. harddisk) cache. Also where "dirty" blocks are stored until written.
swap.label swap
swap.draw STACK
swap.info Swap space used.
cached.label cache
cached.draw STACK
cached.info Parked file data (file content) cache.
free.label unused
free.draw STACK
free.info Wasted memory. Memory that is not used for anything at all.
slab.label slab_cache
slab.draw STACK
slab.info Memory used by the kernel (major users are caches like inode, dentry, etc).
swap_cache.label swap_cache
swap_cache.draw STACK
swap_cache.info A piece of memory that keeps track of pages that have been fetched from swap but not yet been modified.
page_tables.label page_tables
page_tables.draw STACK
page_tables.info Memory used to map between virtual and physical memory addresses.
vmalloc_used.label vmalloc_used
vmalloc_used.draw LINE2
vmalloc_used.info 'VMalloc' (kernel) memory used
committed.label committed
committed.draw LINE2
committed.info The amount of memory allocated to programs. Overcommitting is normal, but may indicate memory leaks.
mapped.label mapped
mapped.draw LINE2
mapped.info All mmap()ed pages.
active.label active
active.draw LINE2
active.info Memory recently used. Not reclaimed unless absolutely necessary.
inactive.label inactive
inactive.draw LINE2
inactive.info Memory not currently used.

multigraph

multigraph uptime
graph_title Uptime
graph_args --base 1000 -l 0
graph_scale no
graph_vlabel uptime in days
graph_category system
uptime.label uptime
uptime.draw AREA
multigraph

multigraph Munin_Time
graph_title Munin Processing Time
graph_vlabel ms
graph_info This graph shows how much time is spent running the munin service, its data is delayed by one run.
graph_category munin
graph_scale no
time.label Service
time.draw LINE
time.info Time Spent running the munin service
plugin.label Plugin
plugin.draw LINE
plugin.info Time Spent running the munin plugins
upload.label Upload
upload.draw LINE
upload.info Time Spent uploading munin data

multigraph Cell_Signal
graph_title Signal Stregth
graph_args --upper-limit 31 -l 0
graph_scale no
graph_vlabel ASU
graph_category Android Phone
graph_info This graph shows Cellular Signal in ASU
signal.label Signal

And here it is without config: "munin-run android_e8XXXXxx"
Android Uptime
Battery
CPU

Load
Memory

uptime

Munin Time
Cell Signal
multigraph Android_Uptime
booted.value 0.5606172
awake.value 0.55164117
multigraph Battery
battery.value 80.0
charge.value 100
multigraph Battery_Temp
temp.value 39.0
multigraph Battery_Volt
volt.value 3.0
multigraph CPU
user.value 2.0293653
nice.value 0.7089339
system.value 1.0785203
idle.value 96.18318
iowait.value 0.7425327
irq.value 0.0067197527
softirq.value 0.013439505
steal.value 0.0
multigraph
multigraph
multigraph
multigraph
multigraph
multigraph Load
load.value 0.05
multigraph Memory
slab.value 13717504
swap_cache.value 0
page_tables.value 14188544
vmalloc_used.value 99811328
apps.value 319012864
free.value 5795840
buffers.value 16269312
cached.value 131485696
swap.value 0
committed.value 2437464064
mapped.value 68685824
active.value 189800448
inactive.value 200503296
multigraph
multigraph uptime
uptime.value 0.5605882
multigraph
multigraph Munin_Time
time.value 1109
plugin.value 107
upload.value 1710
multigraph Cell_Signal
signal.value 55

**Comment by silverchris** [comment]
ok, that should be fixed in the latest android_ munin plugin, let me know if it solves it

**Comment by lthown** [comment]
Firewall graph isn't showing anything but the network one is working great now.

**Comment by silverchris** [comment]
is the firewall graph showing nan or 0 ?

**Comment by lthown** [comment]
-nan

**Comment by silverchris** [comment]
an you get the output of cat /proc/net/snmp on your phone? specifically the line that starts with Ip: it should be the second line

**Comment by lthown** [comment]
# cat /proc/net/snmp

cat /proc/net/snmp
Ip: Forwarding DefaultTTL InReceives InHdrErrors InAddrErrors ForwDatagrams InUnknownProtos InDiscards InDelivers OutRequests OutDiscards OutNoRoutes ReasmTimeout ReasmReqds ReasmOKs ReasmFails
FragOKs FragFails FragCreates
Ip: 2 64 771369 0 74 0 0 0 771295 470893 0 2024 0 0 0 0 0 0 0
Icmp: InMsgs InErrors InDestUnreachs InTimeExcds InParmProbs InSrcQuenchs InRedirects InEchos InEchoReps InTimestamps InTimestampReps InAddrMasks InAddrMaskReps OutMsgs OutErrors OutDestUnreachs OutTimeExcds OutParmProbs OutSrcQuenchs OutRedirects OutEchos OutEchoReps OutTimestamps OutTimestampReps OutAddrMasks OutAddrMaskReps
Icmp: 80 0 80 0 0 0 0 0 0 0 0 0 0 76 0 76 0 0 0 0 0 0 0 0 0 0
IcmpMsg: InType3 OutType3
IcmpMsg: 80 76
Tcp: RtoAlgorithm RtoMin RtoMax MaxConn ActiveOpens PassiveOpens AttemptFails EstabResets CurrEstab InSegs OutSegs RetransSegs InErrs OutRsts
Tcp: 1 195 120000 -1 4180 10 212 520 4 765674 468776 1358 0 650
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors
Udp: 2479 1 0 2629 0 0
UdpLite: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors
UdpLite: 0 0 0 0 0 0

**Comment by silverchris** [comment]
hmmm, from a quick look it should still work. can you get the output from "munin-run android_eXxXXxxX config" and "munin-run android_eXxXXxxX" again. It looks like last time you had the firewall plugin disabled?
